services:
- type: web
  name: Danam-kittiya-pashuvinta-pall-ennano-1
  runtime: python
  repo: https://github.com/rohith-0099/Danam-kittiya-pashuvinta-pall-ennano
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: streamlit run app.py
  autoDeployTrigger: commit
version: "1"
